export const goalieCareerColumns = (width) => {
    const columnWidth = width ? width : '120'
    const columns = [       
        {
            field:'year',
            headerName:'YEAR',
            width:columnWidth,
        },
        {
            field:'team',
            headerName:'TEAM',
            width:columnWidth,
        },
        {
            field:'league',
            headerName:'LG',
            width:columnWidth,
        },
        {
            field:'games',
            headerName:'GP',
            width:columnWidth,
        },
       {
            field:'minutes',
            headerName:'MIN',
            width:columnWidth
        },
        {
            field:'wins',
            headerName:'W',
            width:columnWidth
        },
        {
            field:'losses',
            headerName:'L',
            width:columnWidth
        },
        {
            field:'ot',
            headerName:'T/OTL',
            width:columnWidth
        },
        {
            field:'shotsAgainst',
            headerName:'SHOTS',
            width:columnWidth
        },
        {
            field:'saves',
            headerName:'SVS',
            width:columnWidth
        },
        {
            field:'goalsAgainst',
            headerName:'GA',
            width:columnWidth
        },
        {
            field:'goalsAgainstAverage',
            headerName:'GAA',
            width:columnWidth
        },
        {
            field:'shutouts',
            headerName:'SO',
            width:columnWidth
        },
        {
            field:'savePercentage',
            headerName:'SV%',
            width:columnWidth
        }
    ]
    return columns
}