export const playerGamesColumns = (width, chart=false) => {
    const columnWidth = width ? width : '120'
    const columns = [
        {
            field:'date',
            headerName:'DT',
            width:columnWidth + 50,
            sortComparator: (v1, v2, param1, param2) =>
                new Date(v2) - new Date(v1)
        },
        {
            field:'league',
            headerName:'LG',
            width:columnWidth,
        },
        {
            field:'teamHome',
            headerName:"H",
            width:columnWidth
        },
        {
            field:'teamAway',
            headerName:"A",
            width:columnWidth
        },
        {
            field:'goals',
            headerName:"G",
            width:columnWidth
        },
        {
            field:'assists',
            headerName:"A",
            width:columnWidth
        },
        {
            field:'points',
            headerName:"PTS",
            width:columnWidth,
        },
        {
            field:'plusMinus',
            headerName:"+/-",
            width:columnWidth
        },
        {
            field:'shots',
            headerName:"S",
            width:columnWidth
        },
        {
            field:'missedShots',
            headerName:"MS",
            width:columnWidth
        },
        {
            field:'blockedShots',
            headerName:"BS",
            width:columnWidth
        },
        {
            field:'penalties',
            headerName:'PLM',
            width:columnWidth
        },
        {
            field:'hits',
            headerName:'H',
            width:columnWidth,
        },
        {
            field:'takeaways',
            headerName:'TA',
            width:columnWidth
        },
        {
            field:'giveaways',
            headerName:'GA',
            width:columnWidth
        },
        {
            field:'shifts',
            headerName:'SFT',
            width:columnWidth
        },
        {
            field:chart ? 'timeOnIceSeconds' : 'timeOnIce',
            headerName:'TOI',
            width:columnWidth
        },
        {
            field:chart ? 'powerplayTimeOnIceSeconds' : 'powerplayTimeOnIce',
            headerName:'PPTOI',
            width:columnWidth
        },
        {
            field:chart ? 'shorthandedTimeOnIceSeconds' : 'shorthandedTimeOnIce',
            headerName:'SHTOI',
            width:columnWidth
        },
        {
            field:chart ? 'evenStrengthTimeOnIceSeconds' : 'evenStrengthTimeOnIce',
            headerName:'ESTOI',
            width:columnWidth
        },
        {
            field:'faceoffWins',
            headerName:"FOW",
            width:columnWidth
        },
        {
            field:'faceoffPercent',
            headerName:'FO%',
            width:columnWidth
        },
        {
            field:'goalsFirst',
            headerName:'G.1st',
            width:columnWidth
        },
        {
            field:'primaryAssists',
            headerName:"Prim.A",
            width:columnWidth
        },
        {
            field:'secondaryAssists',
            headerName:"Sec.A",
            width:columnWidth
        },
        {
            field:'primaryAssistsFirst',
            headerName:"Prim.A.1st",
            width:columnWidth
        },
        {
            field:'secondaryAssistsFirst',
            headerName:"Sec.A.1st",
            width:columnWidth
        },
        {
            field:'pointsFirst',
            headerName:"PTS.1st",
            width:columnWidth,
        },
        {
            field:'goalsSecond',
            headerName:"G.2nd",
            width:columnWidth
        },
        {
            field:'primaryAssistsSecond',
            headerName:"Prim.A.2nd",
            width:columnWidth
        },
        {
            field:'secondaryAssistsSecond',
            headerName:"Sec.A.2nd",
            width:columnWidth
        },
        {
            field:'pointsSecond',
            headerName:"PTS.2nd",
            width:columnWidth,
        },
        {
            field:'goalsThird',
            headerName:"G.3rd",
            width:columnWidth
        },
        {
            field:'primaryAssistsThird',
            headerName:"Prim.A.3rd",
            width:columnWidth
        },
        {
            field:'secondaryAssistsThird',
            headerName:"Sec.A.3rd",
            width:columnWidth
        },
        {
            field:'pointsThird',
            headerName:"PTS.3rd",
            width:columnWidth,
        },
        {
            field:'goalsOT',
            headerName:"G.OT",
            width:columnWidth
        },
        {
            field:'primaryAssistsOT',
            headerName:"Prim.A.OT",
            width:columnWidth
        },
        {
            field:'secondaryAssistsOT',
            headerName:"Sec.A.OT",
            width:columnWidth
        },
        {
            field:'pointsOT',
            headerName:"PTS.OT",
            width:columnWidth,
        },
        {
            field:'type',
            headerName:'Season',
            width:columnWidth * 2,
        }
    ]
    return columns
}

