import React from 'react'
import { Link } from 'gatsby'

export const playerStatsOtherColumns = (width) => {
    const columnWidth = width ? width : '120'
    const columns = [
        {
            field:'fullName',
            headerName:'Name',
            width:'200',
            renderCell:(params, GridRenderCellParams)=>(
                <Link
                    to="/player"
                    state={{id:params.row.id, teamId:params.row.teamId}}
                >
                    {params.value}
                </Link>
            )
        },
        {
            field:'positions',
            headerName:'POS',
            width:columnWidth
        },
        {
            field:'games',
            headerName:'GP',
            width:columnWidth,
        },
        {
            field:'goalsFirst',
            headerName:'G1',
            width:columnWidth, 
        },
        {
            field:'assistsFirst',
            headerName:'A1',
            width:columnWidth, 
        },
        {
            field:'pointsFirst',
            headerName:'PT1',
            width:columnWidth
        },
        {
            field:'goalsSecond',
            headerName:'G2',
            width:columnWidth, 
        },
        {
            field:'assistsSecond',
            headerName:'A2',
            width:columnWidth, 
        },
        {
            field:'pointsSecond',
            headerName:'PT2',
            width:columnWidth
        },
        {
            field:'goalsThird',
            headerName:'G3',
            width:columnWidth, 
        },
        {
            field:'assistsThird',
            headerName:'A3',
            width:columnWidth
        },
        {
            field:'pointsThird',
            headerName:'PT3',
            width:columnWidth
        },
        {
            field:'goalsOT',
            headerName:'GOT',
            width:columnWidth, 
        },
        {
            field:'assistsOT',
            headerName:'AOT',
            width:columnWidth
        },
        {
            field:'pointsOT',
            headerName:'PTOT',
            width:columnWidth
        },
        {
            field:'primaryAssistsFirst',
            headerName:'PA1',
            width:columnWidth, 
        },
        {
            field:'primaryAssistsSecond',
            headerName:'PA2',
            width:columnWidth, 
        },
        {
            field:'primaryAssistsThird',
            headerName:'PA3',
            width:columnWidth, 
        },
        {
            field:'primaryAssistsOT',
            headerName:'PAOT',
            width:columnWidth, 
        },
        {
            field:'secondaryAssistsFirst',
            headerName:'SA1',
            width:columnWidth, 
        },
        {
            field:'secondaryAssistsSecond',
            headerName:'SA2',
            width:columnWidth, 
        },
        {
            field:'secondaryAssistsThird',
            headerName:'SA3',
            width:columnWidth, 
        },
        {
            field:'secondaryAssistsOT',
            headerName:'SAOT',
            width:columnWidth, 
        },
        {
            field:'pdo',
            headerName:'PDO',
            width:columnWidth
        },
        {
            field:'cf',
            headerName:'CF',
            width:columnWidth
        },
        {
            field:'ca',
            headerName:'CA',
            width:columnWidth
        },
        {
            field:'cfPercent',
            headerName:'CF%',
            width:columnWidth
        },
        {
            field:'cfPercentRel',
            headerName:'CF%REL',
            width:columnWidth
        },
        {
            field:'ff',
            headerName:'FF',
            width:columnWidth
        },
        {
            field:'fa',
            headerName:'FF',
            width:columnWidth
        },
        {
            field:'ffPercent',
            headerName:'FF%',
            width:columnWidth
        },
        {
            field:'ffPercentRel',
            headerName:'FF%REL',
            width:columnWidth
        }
    ]
    return columns
}