export const playerCareerColumns = (width, chart=false) => {
    const columnWidth = width ? width : '120'
    const columns = [
        {
            field:'year',
            headerName:'YR',
            width:columnWidth,
        },
        {
            field:'team',
            headerName:'TM',
            width:columnWidth,
        },
        {
            field:'league',
            headerName:'LG',
            width:columnWidth,
        },
        {
            field:'games',
            headerName:'GP',
            width:columnWidth,
        },
        {
            field:'goals',
            headerName:'G',
            width:columnWidth, 
        },
        {
            field:'assists',
            headerName:'A',
            width:columnWidth,
        },
        {
            field:'points',
            headerName:'PTS',
            width:columnWidth,
        },
        {
            field:'plusMinus',
            headerName:'+/-',
            width:columnWidth,
        },
        {
            field:'penalties',
            headerName:'PLM',
            width:columnWidth,
        },
        {
            field:'powerplayGoals',
            headerName:'PPG',
            width:columnWidth,
        },
        {
            field:'powerplayAssists',
            headerName:'PPA',
            width:columnWidth,
        },
        {
            field:'powerplayPoints',
            headerName:'PPG',
            width:columnWidth,
        },
        {
            field:'shorthandedGoals',
            headerName:'SHG',
            width:columnWidth,
        },
        {
            field:'shorthandedAssists',
            headerName:'SHA',
            width:columnWidth,
        },
        {
            field:'shorthandedPoints',
            headerName:'SHP',
            width:columnWidth,
        },
        {
            field:'fights',
            headerName:'FT',
            width:columnWidth,
        },
        {
            field:'fightsWon',
            headerName:'FTW',
            width:columnWidth,
        },
        {
            field:'fightWinPercent',
            headerName:'FTW%',
            width:columnWidth,
        },
        {
            field:'hits',
            headerName:'H',
            width:columnWidth,
        },
        {
            field:'giveaways',
            headerName:'GA',
            width:columnWidth,
        },
        {
            field:'takeaways',
            headerName:'TA',
            width:columnWidth,
        },
        {
            field:'shotsBlocked',
            headerName:'SB',
            width:columnWidth,
        },
        {
            field:'gameRating',
            headerName:'GR',
            width:columnWidth,
        },
        {
            field:'shots',
            headerName:'S',
            width:columnWidth,
        },
        {
            field:chart ? 'timeOnIcePerGameSeconds' : 'timeOnIcePerGame',
            headerName:'TOI',
            width:columnWidth
        },
        {
            field:'goalsFor60',
            headerName:'G/60MIN',
            width:columnWidth
        },
        {
            field:'shotsFor60',
            headerName:'S60/MIN',
            width:columnWidth
        },
        {
            field:'gameWinningGoals',
            headerName:'GWG',
            width:columnWidth
        },
        {
            field:'faceoffs',
            headerName:'FO',
            width:columnWidth
        },
        {
            field:'faceoffsWon',
            headerName:'FOW',
            width:columnWidth
        },
        {
            field:'faceoffWinPercent',
            headerName:'FO%',
            width:columnWidth
        },
        {
            field:'powerplayTimeOnIce',
            headerName:'PPTOI',
            width:columnWidth,
        },
        {
            field:'powerplayTimeOnIcePerGame',
            headerName:'PPTOI/GP',
            width:columnWidth,
        },
        {
            field:'shorthandedTimeOnIce',
            headerName:'SHTOI',
            width:columnWidth
        }
    ]
    return columns
}