export const playerColumns = (width) => {
    const columnWidth = width ? width : '120'
    const columns = [
        {
            field:'fullName',
            headerName:'Name',
            width:'200',
        },
        {
            field:'positions',
            headerName:'POS',
            width:columnWidth
        },
        {
            field:'games',
            headerName:'GP',
            width:columnWidth,
        },
        {
            field:'goals',
            headerName:'G',
            width:columnWidth, 
        },
        {
            field:'assists',
            headerName:'A',
            width:columnWidth,
        },
        {
            field:'points',
            headerName:'PTS',
            width:columnWidth,
        },
        {
            field:'goalsFirst',
            headerName:'G1',
            width:columnWidth, 
        },
        {
            field:'goalsSecond',
            headerName:'G2',
            width:columnWidth, 
        },
        {
            field:'goalsThird',
            headerName:'G3',
            width:columnWidth, 
        },
        {
            field:'goalsOT',
            headerName:'GOT',
            width:columnWidth, 
        },
                {
            field:'assistsFirst',
            headerName:'A1',
            width:columnWidth, 
            valueGetter:(params)=>(parseInt(params.getValue(params.id, 'primaryAssistsFirst')) + parseInt(params.getValue(params.id, 'secondaryAssistsFirst')))
        },
        {
            field:'assistsSecond',
            headerName:'A2',
            width:columnWidth, 
            valueGetter:(params)=>(parseInt(params.getValue(params.id, 'primaryAssistsSecond')) + parseInt(params.getValue(params.id, 'secondaryAssistsSecond')))
        },
        {
            field:'assistsThird',
            headerName:'A3',
            width:columnWidth, 
            valueGetter:(params)=>(parseInt(params.getValue(params.id, 'primaryAssistsThird')) + parseInt(params.getValue(params.id, 'secondaryAssistsThird')))
        },
        {
            field:'assistsOT',
            headerName:'AOT',
            width:columnWidth, 
            valueGetter:(params)=>(parseInt(params.getValue(params.id, 'primaryAssistsOT')) + parseInt(params.getValue(params.id, 'secondaryAssistsOT')) || 0)
        },
        {
            field:'primaryAssistsFirst',
            headerName:'PA1',
            width:columnWidth, 
        },
        {
            field:'primaryAssistsSecond',
            headerName:'PA2',
            width:columnWidth, 
        },
        {
            field:'primaryAssistsThird',
            headerName:'PA3',
            width:columnWidth, 
        },
        {
            field:'primaryAssistsOT',
            headerName:'PAOT',
            width:columnWidth, 
        },
        {
            field:'secondaryAssistsFirst',
            headerName:'SA1',
            width:columnWidth, 
        },
        {
            field:'secondaryAssistsSecond',
            headerName:'SA2',
            width:columnWidth, 
        },
        {
            field:'secondaryAssistsThird',
            headerName:'SA3',
            width:columnWidth, 
        },
        {
            field:'secondaryAssistsOT',
            headerName:'SAOT',
            width:columnWidth, 
        },
        {
            field:'pointsFirst',
            headerName:'PT1',
            width:columnWidth, 
            valueGetter:(params)=>(parseInt(params.getValue(params.id, 'goalsFirst')) + parseInt(params.getValue(params.id, 'primaryAssistsFirst')) + parseInt(params.getValue(params.id, 'secondaryAssistsFirst')))
        },
        {
            field:'pointsSecond',
            headerName:'PT2',
            width:columnWidth, 
            valueGetter:(params)=>(parseInt(params.getValue(params.id, 'goalsSecond')) + parseInt(params.getValue(params.id, 'primaryAssistsSecond')) + parseInt(params.getValue(params.id, 'secondaryAssistsSecond')))
        },
        {
            field:'pointsThird',
            headerName:'PT3',
            width:columnWidth, 
            valueGetter:(params)=>(parseInt(params.getValue(params.id, 'goalsThird')) + parseInt(params.getValue(params.id, 'primaryAssistsThird')) + parseInt(params.getValue(params.id, 'secondaryAssistsThird')))
        },
        {
            field:'pointsOT',
            headerName:'PTOT',
            width:columnWidth, 
            valueGetter:(params)=>(parseInt(params.getValue(params.id, 'goalsOT')) + parseInt(params.getValue(params.id, 'primaryAssistsOT')) + parseInt(params.getValue(params.id, 'secondaryAssistsOT')) || 0)
        },
        {
            field:'plusMinus',
            headerName:'+/-',
            width:columnWidth,
        },
        {
            field:'penalties',
            headerName:'PLM',
            width:columnWidth,
        },
        {
            field:'powerplayGoals',
            headerName:'PPG',
            width:columnWidth,
        },
        {
            field:'powerplayAssists',
            headerName:'PPA',
            width:columnWidth,
        },
        {
            field:'powerplayPoints',
            headerName:'PPG',
            width:columnWidth,
        },
        {
            field:'shorthandedGoals',
            headerName:'SHG',
            width:columnWidth,
        },
        {
            field:'shorthandedAssists',
            headerName:'SHA',
            width:columnWidth,
        },
        {
            field:'shorthandedPoints',
            headerName:'SHP',
            width:columnWidth,
        },
        {
            field:'fights',
            headerName:'FT',
            width:columnWidth,
        },
        {
            field:'fightsWon',
            headerName:'FTW',
            width:columnWidth,
        },
        {
            field:'fightWinPercent',
            headerName:'FTW%',
            width:columnWidth,
        },
        {
            field:'hits',
            headerName:'H',
            width:columnWidth,
        },
        {
            field:'takeaways',
            headerName:'TA',
            width:columnWidth,
        },
        {
            field:'giveaways',
            headerName:'GA',
            width:columnWidth,
        },
        {
            field:'shotsBlocked',
            headerName:'SB',
            width:columnWidth,
        },
        {
            field:'gameRating',
            headerName:'GR',
            width:columnWidth,
        },
        {
            field:'gameRatingOffense',
            headerName:'OR',
            width:columnWidth,
        },
        {
            field:'gameRatingDefense',
            headerName:'DR',
            width:columnWidth,
        },
        {
            field:'shots',
            headerName:'S',
            width:columnWidth,
        },
        {
            field:'timeOnIcePerGame',
            headerName:'toi',
            width:columnWidth,
        },
        {
            field:'powerplayTimeOnIcePerGame',
            headerName:'pptoi',
            width:columnWidth,
        },
        {
            field:'shorthandedTimeOnIcePerGame',
            headerName:'shtoi',
            width:columnWidth
        },
        {
            field:'pdo',
            headerName:'pdo',
            width:columnWidth
        },
        {
            field:'goalsFor60',
            headerName:'g60',
            width:columnWidth
        },
        {
            field:'goalsAgainst60',
            headerName:'ga60',
            width:columnWidth
        },
        {
            field:'shotsFor60',
            headerName:'s60',
            width:columnWidth
        },
        {
            field:'shotsAgainst60',
            headerName:'sa60',
            width:columnWidth
        },
        {
            field:'cf',
            headerName:'cf',
            width:columnWidth
        },
        {
            field:'ca',
            headerName:'ca',
            width:columnWidth
        },
        {
            field:'cfPercent',
            headerName:'cf%',
            width:columnWidth
        },
        {
            field:'cfPercentRel',
            headerName:'cf%rel',
            width:columnWidth
        },
        {
            field:'ff',
            headerName:'ff',
            width:columnWidth
        },
        {
            field:'fa',
            headerName:'fa',
            width:columnWidth
        },
        {
            field:'ffPercent',
            headerName:'ff%',
            width:columnWidth
        },
        {
            field:'ffPercentRel',
            headerName:'ff%rel',
            width:columnWidth
        },
        {
            field:'ffPercentRel',
            headerName:'ff%rel',
            width:columnWidth
        },
        {
            field:'gameWinningGoals',
            headerName:'gwg',
            width:columnWidth
        },
        {
            field:'faceoffs',
            headerName:'fo',
            width:columnWidth
        },
        {
            field:'faceoffsWon',
            headerName:'fow',
            width:columnWidth
        },
        {
            field:'faceoffWinPercent',
            headerName:'fow%',
            width:columnWidth
        },
    ]
    return columns
}